### PR TITLE
(257705547) Feature/ZW-1359 CSP & Travis Pipeline

### PR DESCRIPTION
**Pull request by Ericky14**
# Changes
- Added CSP.
- Added travis pipeline config.

### CODE REVIEW

**Comment by cronicc** [comment]
The explorer urls need to be allowed in CSP, they are also user configurable. Not sure if we can make the CSP tags dynamic to allow changing them.

**Comment by Ericky14** [comment]
@cronicc The only way to make those dynamic is to have them served by the backend.
https://gist.github.com/plentz/6737338
Otherwise we could also manipulate the DOM manually, but not sure this is ideal.

**Comment by cronicc** [comment]
@Ericky14 we'd like to keep the site static. So for now just allow the default explorer urls in CSP. I'll create a separate issue for how to handle explorer config options.

Edit; issue https://github.com/ZencashOfficial/myzenwallet/issues/44  created

**Comment by Ericky14** [comment]
@cronicc I added the default explorer urls to the travis env var for CSP. Do you want me to add it to the code instead?

**Comment by cronicc** [comment]
@Ericky14 I'd like to have it in the code, so that 3rd parties can potentially add other explorers.

**Comment by Ericky14** [comment]
@cronicc Done

**Pull request closed without merging**
